server {
    listen 80;
    server_name SITE_NAME;
    charset utf-8;

    access_log /home/ubuntu/SITE_NAME/logs/access.log;
    error_log /home/ubuntu/SITE_NAME/logs/error.log;

    location /favicon.ico { access_log off; log_not_found off; }

    location /robots.txt {
        alias /home/ubuntu/SITE_NAME/robots.txt;
    }

    location /static {
        alias /home/ubuntu/SITE_NAME/static;
    }

    location / {
        proxy_set_header Host $host;
        proxy_pass http://unix:/home/ubuntu/SITE_NAME/gunicorn.sock;
    }
}