# Generated by Django 3.0.2 on 2020-01-12 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='이름')),
                ('oily', models.CharField(blank=True, max_length=1, verbose_name='지성영향')),
                ('dry', models.CharField(blank=True, max_length=1, verbose_name='건성영향')),
                ('sensitive', models.CharField(blank=True, max_length=1, verbose_name='민감성영향')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imageId', models.CharField(max_length=128, verbose_name='상품 이미지 ID')),
                ('name', models.CharField(max_length=128, verbose_name='상품명')),
                ('price', models.PositiveIntegerField(verbose_name='가격')),
                ('gender', models.CharField(choices=[('male', '남'), ('female', '여'), ('all', '구분없음')], max_length=8, verbose_name='성별')),
                ('category', models.CharField(choices=[('skincare', '스킨케어'), ('maskpack', '마스크팩'), ('suncare', '선케어'), ('basemakeup', '베이스메이크업')], max_length=16, verbose_name='카테고리')),
                ('monthlySales', models.PositiveIntegerField(verbose_name='이번 달 판매 수량')),
                ('ingredients', models.ManyToManyField(blank=True, related_name='products', to='product.Ingredient', verbose_name='구성성분')),
            ],
        ),
    ]
